### ISSUE TITLE
http://repo.blha303.biz Does not have updated Minecraft-Reflection.

### ISSUE THREAD

**Issue by harrydevane** [CaptainBern/Reflection#8]
http://repo.blha303.biz currently does not have an updated Miinecraft-Reflection jar, causing the memory leak fix(https://github.com/CaptainBern/Reflection/commit/971546f9b8873934ceca6fc9eca378a878e258cf) to not be included in projects such as EchoPet, could we get this fixed please?

**Comment by CaptainBern** [comment]
Oh right. I'm not sure if I have access to that repo/jenkins instance it's pulling the items from but I'll contact blha303 and ask if he can update.

**Comment by DSH105** [comment]
As discussed [here](https://github.com/DSH105/EchoPet/pull/542), the maven repo is inactive. I'm currently looking into alternatives and @blha303 is investigating the potential of a GitHub-based solution.

**Comment by CaptainBern** [comment]
I've created a new item on @DSH105 's [Jenkins](https://ci.dsh105.com/view/CaptainBern/). As soon as it's configured properly and actually builds we'll use that in EchoPet.

**Comment by CharlesVien** [comment]
This is still causing us issues, is there any update on this yet?

**Comment by CaptainBern** [comment]
Apologies, completely forgot about this. We need to fix EchoPet too since it's still using the wrong repo I think. At the moment my builds are still failing so I guess @DSH105 can take a look at it maybe (please dsh <3)

**Comment by DSH105** [comment]
will do cap'n

**Comment by CaptainBern** [comment]
Updated the thingy. @DSH105 I can't seem to be able to trigger a new build, maybe my permissions for adjusted or maybe the slave is offline. 

As soon as it compiles, all projects should use DSH105's maven repo instead of blha303's. (Tho I'll look into updating that one too when I find the time for it)

**Comment by DSH105** [comment]
I checked the permissions and you should be still able to build stuff

**Comment by CaptainBern** [comment]
The build was successful! I triggered a new EchoPet build too, you can download the _fixed_ build [here](https://ci.dsh105.com/job/EchoPet-v2/68/).

I will close this now as it's fixed. Thanks for reporting this @Harry5573 & @CharlesVien
